import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const video = '/hero.mp4'
const videoWeb = '/hero.webm'
const hero = '/assets/hero.jpg'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative w-full h-full overflow-auto'
        style={{ backgroundColor: 'rgb(8, 18, 10)' }}>
        <div className='absolute top-0 left-0 w-full h-screen bg-black/60 z-10 ' />
        <video
          autoPlay
          loop
          muted
          preload="auto"
          poster={hero}
        >
          <source src={video} type="video/mp4" />
          <source src={videoWeb} type="videoWeb/webm" />
        </video>{children}</body>
    </html>
  )
}
